apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: meta-api
  description: Retrieve meta api details
spec:
  type: openapi
  lifecycle: development
  owner: meeran
  system: meta
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists
    ...
