apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Resume builder
  description: The place to be, for great artists
  labels:
    example.com/custom: custom_label_value
  annotations:
     backstage.io/techdocs-ref: dir:.
  tags:
    - javascript
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: website
  lifecycle: Development
  owner: Meeran
  system: public-websites
