apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: a-javascript-library
    description: A javascript Library
    annotations:
        backstage.io/techdocs-ref: dir:.
        github.com/project-slug: pep8speaks-org/pep8speaks
    tags:
        - javascript
    links:
        - url: https://admin.example-org.com
          title: Admin Dashboard
          icon: dashboard
          type: admin-dashboard
spec:
    type: service
    lifecycle: development
    owner: meeran
    system: project-x
    type: url
    target: https://github.com/Meeranmk/ResumeBuilder/blob/main/service_with_docs/catalog-info.yaml
    

---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
    name: project-x
    description: Handy tools to keep artists in the loop
spec:
  owner: meeran
  type: url
  target: https://github.com/Meeranmk/ResumeBuilder/blob/main/service_with_docs/catalog-info.yaml
